### ISSUE TITLE
Don't apply animation pose when exporting Animator with clips

### ISSUE THREAD

**Issue by pdinklag** [Perfare/AssetStudio#336] opened 2018-12-26 15:19 UTC
When I use the _Export Animator with selected AnimationClip_ tool, in the exported FBX, the mesh+skeleton has the pose of the first frame of some (the first?) animation applied. Why is this?

I believe this is the main problem people are facing trying to export humanoid animations (e.g. #267). Even if there is no T-Pose in the animation, can't you just simply enforce the _original_ mesh+skeleton with no pose applied? In most cases, that is the T-Pose or at least it's very similar to it. When re-importing into Unity, you could then create a humanoid avatar from that and get humanoid animation support for free.

The way I see it, you don't have to do much: if I export an Animator with no animation clips, the FBX contains the mesh+skeleton in default pose exactly like I want it - so that functionality is already there. Instead of applying the first animation's first frame on it, just export the same default pose even when animation clips are selected.

**Comment by Perfare** [comment] 2018-12-26 16:04
AssetStudio does not change the default pose, whether or not you choose to export the animation.
But why has the pose of the first frame? I don't know why, maybe it's some reason for fbx. The solution see #303

**Comment by pdinklag** [comment] 2018-12-26 21:52
OK, interesting. When I tell Unity to import the FBX with animation type "None" - then the mesh is in its original pose. Once I tell Unity the animation type is "Legacy" or "Humanoid", it applies the frame on the mesh for no apparent reason.

I guess it's a bug in Unity's importer (2018.3)? Or some FBX setting that should be cleared? If the latter might apply, I could provide the files I'm using if you'd like to have a look.

**Comment by pdinklag** [comment] 2018-12-26 22:04
OK, this can be fixed by exporting the Animator without any animation, import it in Unity and create an avatar for it.

Then export the same Animator WITH animations. When importing the one with animations, copy the avatar from the Animator with no animations. Then, everything seems to work correctly.

**Comment by cesm1980** [comment] 2018-12-27 00:10
In case this fixes the problem with humanoid animations, that would make support for a LOT of 
unity games that i found with kind of animations which are impossible to export from assetstudio or unity itself with the official fbx exporter (it doesn't support humanoid animation support), i only found 2 assets on the asset store that can convert humanoid clip to generic clip this but they are paid, not free.

Altough i WAS able to do play humanoid animations from the game, inside unity itself but i had to use Utiny to extract the animation clips, because with assetstudio it does indeed keep stuck in the first frame and it's like the animations are "empty" if i try to export to fbx.

Regarding the method said above by pdinklag, since i have no idea in how to create a avatar from scratch i used the one from the game itself (extracted too with utiny) but it doesn't work since unity sees the exported fbx from assetstudio as a Generic avatar, and both the animations and avatar from the game unity says they are humanoid. Also i wonder if you are using humanoid or generic animations, if you got the problem it's possible it's humanoid type.

I really hope there's a fix for this because so far the only way to export humanoid animations from unity is paid assets, even the author from Utiny confirmed the same thing too.

**Comment by Perfare** [comment] 2019-01-03 00:09
@cesm1980 I suggest you spend money if you really need these things.

**Closed by Perfare** 2019-01-03 00:09 UTC
